export const ATTEMPT_START_REQUEST = "ATTEMPT_START_REQUEST";
export const ATTEMPT_START_SUCCESS = "ATTEMPT_START_SUCCESS";
export const ATTEMPT_START_FAIL = "ATTEMPT_START_FAIL";

export const ATTEMPT_QUESTIONS_REQUEST = "ATTEMPT_QUESTIONS_REQUEST";
export const ATTEMPT_QUESTIONS_SUCCESS = "ATTEMPT_QUESTIONS_SUCCESS";
export const ATTEMPT_QUESTIONS_FAIL = "ATTEMPT_QUESTIONS_FAIL";

export const ATTEMPT_SUBMIT_REQUEST = "ATTEMPT_SUBMIT_REQUEST";
export const ATTEMPT_SUBMIT_SUCCESS = "ATTEMPT_SUBMIT_SUCCESS";
export const ATTEMPT_SUBMIT_FAIL = "ATTEMPT_SUBMIT_FAIL";

export const ATTEMPT_GET_ALL_REQUEST = "ATTEMPT_GET_ALL_REQUEST";
export const ATTEMPT_GET_ALL_SUCCESS = "ATTEMPT_GET_ALL_SUCCESS";
export const ATTEMPT_GET_ALL_FAIL = "ATTEMPT_GET_ALL_FAIL";

export const ATTEMPT_DELETE_REQUEST = "ATTEMPT_DELETE_REQUEST";
export const ATTEMPT_DELETE_SUCCESS = "ATTEMPT_DELETE_SUCCESS";
export const ATTEMPT_DELETE_FAIL = "ATTEMPT_DELETE_FAIL";
