export const ATTEMPT_START_REQUEST = "ATTEMPT_START_REQUEST";
export const ATTEMPT_START_SUCCESS = "ATTEMPT_START_SUCCESS";
export const ATTEMPT_START_FAIL = "ATTEMPT_START_FAIL";

export const ATTEMPT_QUESTIONS_REQUEST = "ATTEMPT_QUESTIONS_REQUEST";
export const ATTEMPT_QUESTIONS_SUCCESS = "ATTEMPT_QUESTIONS_SUCCESS";
export const ATTEMPT_QUESTIONS_FAIL = "ATTEMPT_QUESTIONS_FAIL";

export const ATTEMPT_SUBMIT_REQUEST = "ATTEMPT_SUBMIT_REQUEST";
export const ATTEMPT_SUBMIT_SUCCESS = "ATTEMPT_SUBMIT_SUCCESS";
export const ATTEMPT_SUBMIT_FAIL = "ATTEMPT_SUBMIT_FAIL";
